# Generated by Django 2.2.3 on 2019-07-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_relevance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='relevance',
            field=models.IntegerField(choices=[(1, 'trivial'), (2, 'important')], default=1),
        ),
    ]
